// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use DATABASE_URL - runtime override in lib/prisma.ts will use DATABASE_PRISMA_DATABASE_URL if available
    url: env("DATABASE_URL"),
  },
});
