/**
 * Environment Setup Helper Script
 * Helps create or update .env file with required variables
 * 
 * Usage: tsx scripts/setup-env.ts
 */

import { readFileSync, writeFileSync, existsSync } from "fs";
import { join } from "path";
import { randomBytes } from "crypto";

const envPath = join(process.cwd(), ".env");

// Generate a secure JWT secret
function generateJWTSecret(): string {
  return randomBytes(32).toString("hex");
}

// Default environment variables
const defaultEnv = {
  DATABASE_URL: "file:./prisma/dev.db",
  NEXT_PUBLIC_APP_URL: "http://localhost:3000",
  NODE_ENV: "development",
  JWT_SECRET: generateJWTSecret(),
  JWT_EXPIRES_IN: "7d",
};

console.log("🔧 Environment Setup Helper\n");

// Check if .env exists
if (existsSync(envPath)) {
  console.log("✅ .env file already exists");
  
  // Read existing .env
  const existingEnv = readFileSync(envPath, "utf-8");
  
  // Check if JWT_SECRET is missing
  if (!existingEnv.includes("JWT_SECRET=")) {
    console.log("⚠️  JWT_SECRET is missing from .env file");
    console.log("\n📝 Adding JWT_SECRET to .env file...");
    
    const newJWTSecret = generateJWTSecret();
    const updatedEnv = existingEnv.trim() + `\n\n# JWT Secret (auto-generated)\nJWT_SECRET=${newJWTSecret}\n`;
    
    writeFileSync(envPath, updatedEnv);
    console.log("✅ JWT_SECRET has been added to .env file");
    console.log(`\n🔑 Generated JWT_SECRET: ${newJWTSecret}`);
    console.log("\n⚠️  IMPORTANT: Keep this secret secure and never commit it to version control!");
  } else {
    console.log("✅ JWT_SECRET is already set in .env file");
  }
} else {
  console.log("📝 Creating .env file...");
  
  // Create .env file with default values
  const envContent = Object.entries(defaultEnv)
    .map(([key, value]) => `${key}=${value}`)
    .join("\n");
  
  const fullEnvContent = `# Environment Variables for Pak-Exporters
# Generated by setup-env.ts

${envContent}

# Optional: Email Service Configuration
# SMTP_HOST=smtp.gmail.com
# SMTP_PORT=587
# SMTP_USER=your-email@gmail.com
# SMTP_PASSWORD=your-app-password
# SMTP_FROM=noreply@pak-exporters.com

# Optional: Analytics
# NEXT_PUBLIC_GA_ID=G-XXXXXXXXXX
# NEXT_PUBLIC_SENTRY_DSN=https://...@sentry.io/...

# Optional: AI Features
# OPENAI_API_KEY=sk-...
`;
  
  writeFileSync(envPath, fullEnvContent);
  console.log("✅ .env file created successfully");
  console.log(`\n🔑 Generated JWT_SECRET: ${defaultEnv.JWT_SECRET}`);
  console.log("\n⚠️  IMPORTANT: Keep this secret secure and never commit it to version control!");
}

console.log("\n✅ Environment setup complete!");
console.log("\n📋 Next steps:");
console.log("   1. Review the .env file and adjust values if needed");
console.log("   2. Run: npm run db:generate");
console.log("   3. Run: npm run db:migrate");
console.log("   4. Run: npm run db:seed");
console.log("\n");

